<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ApplyLastLogin</name>
   <tag></tag>
   <elementGuidId>9581bc2e-bc50-4c4b-9b27-305fce4c1997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[10]/div[4]/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
