<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>var_opt1</name>
   <tag></tag>
   <elementGuidId>521d8634-1441-44d4-8f4a-1745bd4105a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[2]/div/div[2]/div[1]/div[3]/div[3]/div[1]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[2]/div/div[2]/div[1]/div[3]/div[3]/div[1]/div[2]/select</value>
   </webElementProperties>
</WebElementEntity>
