<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>a4d837bc-1299-426e-8716-fdf4870a62ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/p[count(. | //p[@ref_element = 'Object Repository/FIND/SELLER/Add Item/Custom Fields/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset']) = count(//p[@ref_element = 'Object Repository/FIND/SELLER/Add Item/Custom Fields/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FIND/SELLER/Add Item/Custom Fields/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
   </webElementXpaths>
</WebElementEntity>
